"""empty message

Revision ID: 1c4363e02fe1
Revises: a4e96b89237e
Create Date: 2024-09-26 00:33:35.529086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4363e02fe1'
down_revision: Union[str, None] = 'a4e96b89237e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('instance_cluster_uuid', 'instances', type_='unique')
    op.create_unique_constraint('webapp_deploy_cluster_id', 'instances', ['cluster_id', 'webapp_deploy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('webapp_deploy_cluster_id', 'instances', type_='unique')
    op.create_unique_constraint('instance_cluster_uuid', 'instances', ['cluster_id', 'uuid'])
    # ### end Alembic commands ###
