"""empty message

Revision ID: 55869b23cb8a
Revises: 
Create Date: 2024-09-29 01:53:07.632646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55869b23cb8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_environments_id'), 'environments', ['id'], unique=False)
    op.create_index(op.f('ix_environments_name'), 'environments', ['name'], unique=True)
    op.create_table('namespaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_namespaces_id'), 'namespaces', ['id'], unique=False)
    op.create_index(op.f('ix_namespaces_name'), 'namespaces', ['name'], unique=True)
    op.create_table('workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_workloads_id'), 'workloads', ['id'], unique=False)
    op.create_index(op.f('ix_workloads_name'), 'workloads', ['name'], unique=True)
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_address', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_address'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('uuid', name='uix_cluster_uuid')
    )
    op.create_index(op.f('ix_clusters_id'), 'clusters', ['id'], unique=False)
    op.create_index(op.f('ix_clusters_name'), 'clusters', ['name'], unique=True)
    op.create_table('webapps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('namespace_id', sa.Integer(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace_id', 'name', name='uix_namespace_name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_webapps_id'), 'webapps', ['id'], unique=False)
    op.create_index(op.f('ix_webapps_name'), 'webapps', ['name'], unique=False)
    op.create_table('webapp_deploys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('webapp_id', sa.Integer(), nullable=False),
    sa.Column('workload_id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('cpu_scaling_threshold', sa.Integer(), nullable=True),
    sa.Column('memory_scaling_threshold', sa.Integer(), nullable=True),
    sa.Column('custom_metrics', sa.JSON(), nullable=False),
    sa.Column('endpoints', sa.JSON(), nullable=False),
    sa.Column('envs', sa.JSON(), nullable=True),
    sa.Column('secrets', sa.JSON(), nullable=True),
    sa.Column('healthcheck', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['webapp_id'], ['webapps.id'], ),
    sa.ForeignKeyConstraint(['workload_id'], ['workloads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'webapp_id', name='uix_environment_uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_webapp_deploys_id'), 'webapp_deploys', ['id'], unique=False)
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('webapp_deploy_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['webapp_deploy_id'], ['webapp_deploys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'webapp_deploy_id', name='webapp_deploy_cluster_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_instances_id'), 'instances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instances_id'), table_name='instances')
    op.drop_table('instances')
    op.drop_index(op.f('ix_webapp_deploys_id'), table_name='webapp_deploys')
    op.drop_table('webapp_deploys')
    op.drop_index(op.f('ix_webapps_name'), table_name='webapps')
    op.drop_index(op.f('ix_webapps_id'), table_name='webapps')
    op.drop_table('webapps')
    op.drop_index(op.f('ix_clusters_name'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_index(op.f('ix_workloads_name'), table_name='workloads')
    op.drop_index(op.f('ix_workloads_id'), table_name='workloads')
    op.drop_table('workloads')
    op.drop_index(op.f('ix_namespaces_name'), table_name='namespaces')
    op.drop_index(op.f('ix_namespaces_id'), table_name='namespaces')
    op.drop_table('namespaces')
    op.drop_index(op.f('ix_environments_name'), table_name='environments')
    op.drop_index(op.f('ix_environments_id'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
