"""empty message

Revision ID: 808502f3061c
Revises: 1c4363e02fe1
Create Date: 2024-09-28 16:49:48.611506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808502f3061c'
down_revision: Union[str, None] = '1c4363e02fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_environment_uuid', 'webapp_deploys', type_='unique')
    op.create_unique_constraint('uix_environment_uuid', 'webapp_deploys', ['environment_id', 'webapp_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_environment_uuid', 'webapp_deploys', type_='unique')
    op.create_unique_constraint('uix_environment_uuid', 'webapp_deploys', ['environment_id', 'uuid'])
    # ### end Alembic commands ###
