"""empty message

Revision ID: 8df2d28ba757
Revises: dfe7c8d9ece4
Create Date: 2024-11-10 16:28:50.007042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8df2d28ba757'
down_revision: Union[str, None] = 'dfe7c8d9ece4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webapp_deploys', 'cpu',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webapp_deploys', 'cpu',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
