"""empty message

Revision ID: b94108b71f2b
Revises: 8df2d28ba757
Create Date: 2024-11-10 16:34:24.882245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94108b71f2b'
down_revision: Union[str, None] = '8df2d28ba757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webapp_deploys', 'cpu',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webapp_deploys', 'cpu',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
