"""empty message

Revision ID: dfe7c8d9ece4
Revises: 33c512f59334
Create Date: 2024-11-10 16:12:13.902737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe7c8d9ece4'
down_revision: Union[str, None] = '33c512f59334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webapp_deploys', sa.Column('cpu', sa.Integer(), nullable=True))
    op.add_column('webapp_deploys', sa.Column('memory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webapp_deploys', 'memory')
    op.drop_column('webapp_deploys', 'cpu')
    # ### end Alembic commands ###
